### ISSUE TITLE
Questionning about groups and grouping strategy

### ISSUE THREAD

**Issue by vfremaux** [juacas/moodle-mod_treasurehunt#47]
Hi Juan

as we keep going testing the plugin we were wondering why the "per group" strategy was designed over the "groupings" concept. Groupings are usually used in moodle to dispatch some activity instances across groupings in the course structure. "Groups" are likely used to alter the "per group" behaviour "inside" the plugin. How question was to know for what reason the grouping principle was choosen to separate hunting groups...

**Comment by juacas** [comment]
Hi,
I'm sorry but I don't understand what you mean with "dispatch some activity instances across groupings"... Sorry.
Anyway, here you have the rationale of our design.
AFAIK the grouping is the way in Moodle for binding a set of groups together for any purpose (i.e. in the module assignments).
When you are designing a Treasurehunt by teams, you need to link each set of groups (teams) to a Road. When you are designing an individual Treasurehunt then you can assign directly a group of users to each Road.
I think that possibility of define different roads is the key for understanding this design.
I hope you enjoy the Treasurehunt.
I will mark this issue as closed because it's not a technical issue (but we keep discussing afterwards if you want).

**Comment by vfremaux** [comment]
thanks for giving your insight. I can understand now the concept of groups as "teams" and using groupings to assign a search path for a set of teams. this makes sense.

 In fact the original design of groupings was to allow some module activities to be available to some subset of the course population, thus dispatching activtity modules across groupings. when it was introduced, groupings were mostly proposed as a "above module scope" feature, while groups where partitionning the participants "inside" the module. Furtherly where introduced accessibility rules that offered more flexible way to give or give not access to some participants using a larger set of condition possibilities.

Comming back to your design, actually the only way to get a "set of groups" architecture is to use the grouping/groups dual organisation level, and actually there is no other way to achieve it.
