### ISSUE TITLE
missing icon and js problems

### ISSUE THREAD

**Issue by llttugraz** [juacas/moodle-mod_treasurehunt#60]
Hi,

We have Moodle v4.1.5 running and recently updated the plugin to the v1.5.5. We encountered following problems after the update:

As you can see in the images attached:
- The icon `mod/treasurehunt/pix/fail_mark.png` is missing and cannot be loaded. I guess, the problem is the wrong icon name.  It should be `failure_mark.png` instead of `fail_mark.png`
- There must be a JavaScript problem, causing the `undefined` output.
- On the map the `minus` icon to zoom out and half of the `plus` button are dropped out of the map and not accessible.

<img width="251" alt="Bildschirmfoto 2023-10-06 um 14 38 56" src="https://github.com/juacas/moodle-mod_treasurehunt/assets/28404082/c96bb8fe-bae8-4fd9-af51-adf4160da510">
<img width="335" alt="Bildschirmfoto 2023-10-06 um 14 39 05" src="https://github.com/juacas/moodle-mod_treasurehunt/assets/28404082/c04dacd8-c2b4-4535-95e2-3ed77441a1bb">
<img width="121" alt="Bildschirmfoto 2023-10-06 um 14 39 50" src="https://github.com/juacas/moodle-mod_treasurehunt/assets/28404082/d2c30019-0130-4694-82dd-359ee22b4f89">

**Comment by juacas** [comment]
Issue is fixed in v1.5.6.
The broken icon is not in the code shoud be fixed in the your language's package (at AMOS https://lang.moodle.org/local/amos/contrib.php).
The term id is 'mapplay_tour'.

<img width="872" alt="image" src="https://github.com/juacas/moodle-mod_treasurehunt/assets/1656180/a4423254-51bf-46ad-aa7e-e7ec17e78a9a">
I've submitted a correction for German/Deuch. If you are using a variant, please submit a change.

Thanks for using this plugin and for reporting.
